name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debugging
        run: |
          echo "logging in using" username: ${{ secrets.DOCKER_USERNAME }} and pass: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/sage-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sage-api:latest

      - name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sage-client:latest

      - name: Deploy to production
        run: |
          echo "Sage is alive"
          # Example: SSH into server and pull/restart containers
          # You'll need to set up appropriate deployment secrets and commands
